"""add year column to book

Revision ID: 0f39d99d6bd7
Revises: 
Create Date: 2025-12-18 03:18:11.491174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f39d99d6bd7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vkusno_and_tochka_burgers')
    op.drop_table('short_urls')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('short_urls',
    sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('long_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('slug', name=op.f('short_urls_pkey'))
    )
    op.create_table('vkusno_and_tochka_burgers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('weight_g', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('calories_kkl', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nutritional_value_kj', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fats_g', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('carbohydrates_g', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('protein_g', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('vkusno_and_tochka_burgers_pkey'))
    )
    # ### end Alembic commands ###
