"""add new data

Revision ID: a22dd75f8225
Revises: 
Create Date: 2025-12-14 10:44:13.094292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a22dd75f8225'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vkusno_and_tochka_burgers')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vkusno_and_tochka_burgers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('weight_g', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('calories_kkl', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nutritional_value_kj', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fats_g', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('carbohydrates_g', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('protein_g', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('vkusno_and_tochka_burgers_pkey'))
    )
    # ### end Alembic commands ###
